import React from 'react';
export const integrationsDetails = () => <div>integrations distinct</div>;
export const integrations_detail_0 = (p:any)=> <div>integrations 0 Square</div>;
export const integrations_detail_1 = (p:any)=> <div>integrations 1 Toast</div>;
export const integrations_detail_2 = (p:any)=> <div>integrations 2 US Foods</div>;
export const integrations_detail_3 = (p:any)=> <div>integrations 3 Sysco</div>;
export const integrations_detail_4 = (p:any)=> <div>integrations 4 Square</div>;
export const integrations_detail_5 = (p:any)=> <div>integrations 5 Toast</div>;
export const integrations_detail_6 = (p:any)=> <div>integrations 6 US Foods</div>;
export const integrations_detail_7 = (p:any)=> <div>integrations 7 Sysco</div>;
export const integrations_detail_8 = (p:any)=> <div>integrations 8 Square</div>;
export const integrations_detail_9 = (p:any)=> <div>integrations 9 Toast</div>;
export const integrations_detail_10 = (p:any)=> <div>integrations 10 US Foods</div>;
export const integrations_detail_11 = (p:any)=> <div>integrations 11 Sysco</div>;
export const integrations_detail_12 = (p:any)=> <div>integrations 12 Square</div>;
export const integrations_detail_13 = (p:any)=> <div>integrations 13 Toast</div>;
export const integrations_detail_14 = (p:any)=> <div>integrations 14 US Foods</div>;
export const integrations_detail_15 = (p:any)=> <div>integrations 15 Sysco</div>;
export const integrations_detail_16 = (p:any)=> <div>integrations 16 Square</div>;
export const integrations_detail_17 = (p:any)=> <div>integrations 17 Toast</div>;
export const integrations_detail_18 = (p:any)=> <div>integrations 18 US Foods</div>;
export const integrations_detail_19 = (p:any)=> <div>integrations 19 Sysco</div>;