import React from 'react';
export const supplierDetails = () => <div>supplier distinct</div>;
export const supplier_detail_0 = (p:any)=> <div>supplier 0 vendors</div>;
export const supplier_detail_1 = (p:any)=> <div>supplier 1 pricing</div>;
export const supplier_detail_2 = (p:any)=> <div>supplier 2 contracts</div>;
export const supplier_detail_3 = (p:any)=> <div>supplier 3 lead time</div>;
export const supplier_detail_4 = (p:any)=> <div>supplier 4 vendors</div>;
export const supplier_detail_5 = (p:any)=> <div>supplier 5 pricing</div>;
export const supplier_detail_6 = (p:any)=> <div>supplier 6 contracts</div>;
export const supplier_detail_7 = (p:any)=> <div>supplier 7 lead time</div>;
export const supplier_detail_8 = (p:any)=> <div>supplier 8 vendors</div>;
export const supplier_detail_9 = (p:any)=> <div>supplier 9 pricing</div>;
export const supplier_detail_10 = (p:any)=> <div>supplier 10 contracts</div>;
export const supplier_detail_11 = (p:any)=> <div>supplier 11 lead time</div>;
export const supplier_detail_12 = (p:any)=> <div>supplier 12 vendors</div>;
export const supplier_detail_13 = (p:any)=> <div>supplier 13 pricing</div>;
export const supplier_detail_14 = (p:any)=> <div>supplier 14 contracts</div>;
export const supplier_detail_15 = (p:any)=> <div>supplier 15 lead time</div>;
export const supplier_detail_16 = (p:any)=> <div>supplier 16 vendors</div>;
export const supplier_detail_17 = (p:any)=> <div>supplier 17 pricing</div>;
export const supplier_detail_18 = (p:any)=> <div>supplier 18 contracts</div>;
export const supplier_detail_19 = (p:any)=> <div>supplier 19 lead time</div>;