import React from 'react';
export const purchasingDetails = () => <div>purchasing distinct</div>;
export const purchasing_detail_0 = (p:any)=> <div>purchasing 0 auto POs</div>;
export const purchasing_detail_1 = (p:any)=> <div>purchasing 1 par levels</div>;
export const purchasing_detail_2 = (p:any)=> <div>purchasing 2 EOQ</div>;
export const purchasing_detail_3 = (p:any)=> <div>purchasing 3 reorder</div>;
export const purchasing_detail_4 = (p:any)=> <div>purchasing 4 auto POs</div>;
export const purchasing_detail_5 = (p:any)=> <div>purchasing 5 par levels</div>;
export const purchasing_detail_6 = (p:any)=> <div>purchasing 6 EOQ</div>;
export const purchasing_detail_7 = (p:any)=> <div>purchasing 7 reorder</div>;
export const purchasing_detail_8 = (p:any)=> <div>purchasing 8 auto POs</div>;
export const purchasing_detail_9 = (p:any)=> <div>purchasing 9 par levels</div>;
export const purchasing_detail_10 = (p:any)=> <div>purchasing 10 EOQ</div>;
export const purchasing_detail_11 = (p:any)=> <div>purchasing 11 reorder</div>;
export const purchasing_detail_12 = (p:any)=> <div>purchasing 12 auto POs</div>;
export const purchasing_detail_13 = (p:any)=> <div>purchasing 13 par levels</div>;
export const purchasing_detail_14 = (p:any)=> <div>purchasing 14 EOQ</div>;
export const purchasing_detail_15 = (p:any)=> <div>purchasing 15 reorder</div>;
export const purchasing_detail_16 = (p:any)=> <div>purchasing 16 auto POs</div>;
export const purchasing_detail_17 = (p:any)=> <div>purchasing 17 par levels</div>;
export const purchasing_detail_18 = (p:any)=> <div>purchasing 18 EOQ</div>;
export const purchasing_detail_19 = (p:any)=> <div>purchasing 19 reorder</div>;