import React from 'react';
export const costingDetails = () => <div>costing distinct</div>;
export const costing_detail_0 = (p:any)=> <div>costing 0 plate cost</div>;
export const costing_detail_1 = (p:any)=> <div>costing 1 margin</div>;
export const costing_detail_2 = (p:any)=> <div>costing 2 food cost %</div>;
export const costing_detail_3 = (p:any)=> <div>costing 3 theoretical</div>;
export const costing_detail_4 = (p:any)=> <div>costing 4 plate cost</div>;
export const costing_detail_5 = (p:any)=> <div>costing 5 margin</div>;
export const costing_detail_6 = (p:any)=> <div>costing 6 food cost %</div>;
export const costing_detail_7 = (p:any)=> <div>costing 7 theoretical</div>;
export const costing_detail_8 = (p:any)=> <div>costing 8 plate cost</div>;
export const costing_detail_9 = (p:any)=> <div>costing 9 margin</div>;
export const costing_detail_10 = (p:any)=> <div>costing 10 food cost %</div>;
export const costing_detail_11 = (p:any)=> <div>costing 11 theoretical</div>;
export const costing_detail_12 = (p:any)=> <div>costing 12 plate cost</div>;
export const costing_detail_13 = (p:any)=> <div>costing 13 margin</div>;
export const costing_detail_14 = (p:any)=> <div>costing 14 food cost %</div>;
export const costing_detail_15 = (p:any)=> <div>costing 15 theoretical</div>;
export const costing_detail_16 = (p:any)=> <div>costing 16 plate cost</div>;
export const costing_detail_17 = (p:any)=> <div>costing 17 margin</div>;
export const costing_detail_18 = (p:any)=> <div>costing 18 food cost %</div>;
export const costing_detail_19 = (p:any)=> <div>costing 19 theoretical</div>;